# SessionEnd hook - the automatic replacement for the old manual analyze-log.ps1 step.
#
# Reads .claude/logs/cmd.log and:
#   1. Rewrites .claude/context/patterns.md with shell-error -> ok correction pairs.
#   2. Updates .claude/context/status.md's "Last changed" section (recent commands +
#      git log), using the most recent session-start marker as the session boundary.
#
# Fires automatically at the end of every session - nothing to remember to run.

$ErrorActionPreference = 'SilentlyContinue'

$root = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$logFile = Join-Path $root ".claude\logs\cmd.log"
$contextDir = Join-Path $root ".claude\context"
$patternsFile = Join-Path $contextDir "patterns.md"
$statusFile = Join-Path $contextDir "status.md"

if (-not (Test-Path $contextDir)) { New-Item -ItemType Directory -Force -Path $contextDir | Out-Null }

$stdin = [Console]::In.ReadToEnd()
$payload = $null
try { $payload = $stdin | ConvertFrom-Json } catch {}

if (-not (Test-Path $logFile)) { exit 0 }

$entries = Get-Content $logFile -Encoding UTF8 |
    Where-Object { $_.Trim() -ne "" } |
    ForEach-Object { try { $_ | ConvertFrom-Json } catch { $null } } |
    Where-Object { $_ -ne $null }

# Write the session-end marker now, so the NEXT session-end can use it as a boundary.
$endEntry = [ordered]@{
    ts      = (Get-Date -Format "yyyy-MM-ddTHH:mm:ss")
    kind    = "session-end"
    session = if ($payload) { $payload.session_id } else { $null }
    reason  = if ($payload) { $payload.reason } else { $null }
}
$endEntry | ConvertTo-Json -Compress | Add-Content -Path $logFile -Encoding UTF8

$cmdEntries = $entries | Where-Object { $_.kind -in @('ok', 'shell-error', 'build-failure') }

# --- 1. shell-error -> ok correction pairs -> patterns.md ---

$corrections = [System.Collections.Generic.List[pscustomobject]]::new()
for ($i = 0; $i -lt $cmdEntries.Count - 1; $i++) {
    $current = $cmdEntries[$i]
    $next    = $cmdEntries[$i + 1]
    if ($current.kind -eq "shell-error" -and $next.kind -eq "ok") {
        $corrections.Add([pscustomobject]@{
            BadCmd    = $current.cmd
            BadOutput = $current.output
            FixedCmd  = $next.cmd
            Ts        = $current.ts
        })
    }
}

$deduped = $corrections |
    Group-Object BadCmd |
    ForEach-Object {
        $grp = $_.Group | Sort-Object Ts -Descending
        [pscustomobject]@{
            BadCmd    = $grp[0].BadCmd
            FixedCmd  = $grp[0].FixedCmd
            BadOutput = $grp[0].BadOutput
            Count     = $_.Count
        }
    } |
    Sort-Object Count -Descending

function Get-ErrorSummary([string]$output) {
    $lines = $output -split "`n"
    $hit = $lines |
        Where-Object { $_ -match "CommandNotFoundException|is not recognized|ParserError|Cannot find|does not exist|ObjectNotFound|FileNotFoundException" } |
        Select-Object -First 1
    if ($hit) { return $hit.Trim() }
    return ($lines | Where-Object { $_.Trim() -ne "" } | Select-Object -First 1).Trim()
}

$now = Get-Date -Format "yyyy-MM-dd HH:mm"
$plines = [System.Collections.Generic.List[string]]::new()
$plines.Add("---")
$plines.Add("name: Observed shell mistakes and corrections")
$plines.Add("description: Auto-generated by .claude/hooks/session-end.ps1 - do not edit by hand")
$plines.Add("---")
$plines.Add("")
$plines.Add("<!-- Last updated: $now | Total logged runs: $($cmdEntries.Count) | Correction pairs found: $($corrections.Count) -->")
$plines.Add("")

if ($deduped.Count -eq 0) {
    $plines.Add("No shell-level mistakes recorded yet.")
} else {
    $plines.Add("## Shell mistakes made and their corrections")
    $plines.Add("")
    $plines.Add("Before running a command, check if it resembles a bad command below.")
    $plines.Add("")
    foreach ($c in $deduped) {
        $times = if ($c.Count -gt 1) { " (repeated $($c.Count)x)" } else { "" }
        $summary = Get-ErrorSummary $c.BadOutput
        $plines.Add("### $($c.BadCmd)$times")
        $plines.Add("")
        $plines.Add("- **Error:** ``$summary``")
        $plines.Add("- **Corrected form:** ``$($c.FixedCmd)``")
        $plines.Add("")
    }
}

[System.IO.File]::WriteAllText($patternsFile, ($plines -join "`n") + "`n", [System.Text.UTF8Encoding]::new($false))

# --- 2. status.md "Last changed" section, bounded by the last session-start marker ---

$starts = $entries | Where-Object { $_.kind -eq "session-start" }
$lastStart = if ($starts.Count -gt 0) { [datetime]($starts[-1].ts) } else { (Get-Date).AddHours(-24) }

$sessionCmds   = $cmdEntries | Where-Object { [datetime]$_.ts -gt $lastStart -and $_.kind -eq "ok" }
$sessionFailed = $cmdEntries | Where-Object { [datetime]$_.ts -gt $lastStart -and $_.kind -eq "shell-error" }

$sessionLines = [System.Collections.Generic.List[string]]::new()
if ($sessionCmds.Count -gt 0) {
    $cmdSummary = ($sessionCmds | Group-Object cmd | Sort-Object Count -Descending |
        Select-Object -First 5 | ForEach-Object { $_.Name }) -join ", "
    $sessionLines.Add("- Commands run successfully: $cmdSummary")
}
if ($sessionFailed.Count -gt 0) {
    $sessionLines.Add("- Shell mistakes made and corrected: $($sessionFailed.Count)")
}

$gitLog = git -C $root log --oneline -5 2>&1
if ($LASTEXITCODE -eq 0 -and $gitLog) {
    $sessionLines.Add("- Recent commits:")
    $gitLog | ForEach-Object { $sessionLines.Add("  - $_") }
}

$lastChangedBody = if ($sessionLines.Count -gt 0) { $sessionLines -join "`n" } else { "- No commands run this session." }
$newLastChanged = "## Last changed`n`n$lastChangedBody`n"

if (Test-Path $statusFile) {
    $existing = Get-Content $statusFile -Raw -Encoding UTF8
    if ($existing -match "(?s)## Last changed\n.*?(?=\n## |\z)") {
        $existing = $existing -replace "(?s)## Last changed\n.*?(?=\n## |\z)", $newLastChanged
    } else {
        $existing = $existing.TrimEnd() + "`n`n" + $newLastChanged
    }
    [System.IO.File]::WriteAllText($statusFile, $existing, [System.Text.UTF8Encoding]::new($false))
} else {
    $header = "---`nname: Critter Plains session status`ndescription: Auto-generated by .claude/hooks/session-end.ps1 at the end of each session`n---`n`n# Critter Plains - Session Status`n`n"
    [System.IO.File]::WriteAllText($statusFile, $header + $newLastChanged, [System.Text.UTF8Encoding]::new($false))
}

exit 0
